[tool.poetry]
name = "eav-model"
version = "0.1.0"
description = ""
authors = ["DeAngelo Floyd <135054919+delonius22@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
